# Depot CI Migration
#
# Source: .github/workflows/deploy-docs.yml
#
# No changes were necessary.

name: Deploy Docs
# on:
#   push:
#     branches: [main]
#     paths:
#       - "apps/docs/**"
#       - ".github/workflows/deploy-docs.yml"
#       - ".github/workflows/deploy-static-site.yml"
#   pull_request:
#     paths:
#       - "apps/docs/**"
#       - ".github/workflows/deploy-docs.yml"
#       - ".github/workflows/deploy-static-site.yml"
# Required for OIDC authentication to AWS
permissions:
  contents: read
  id-token: write
jobs:
  deploy:
    uses: ./.github/workflows/deploy-static-site.yml
    with:
      site-name: docs
      app-path: apps/docs
      site-infra-workspace: apps/docs/infra
      s3-prefix: docs
    secrets: inherit
