import { gzipSync } from "node:zlib"
import { Buffer } from "node:buffer"

/**
 * Options for generating a shim module.
 */
export interface GenerateShimModuleOptions {
  /** Workspace path (e.g., "core-infrastructure/vpc") */
  workspacePath: string
  /** State version serial number */
  serial: number
  /** Outputs from the state version (JSON from the outputs column) */
  outputs: Record<string, unknown> | null
}

/**
 * Terraform state output format.
 * This is what we extract from the state file's outputs.
 */
interface TerraformOutput {
  value: unknown
  type?: unknown
  sensitive?: boolean
}

/**
 * Generate a shim module as a tar.gz archive.
 *
 * The shim module contains:
 * - main.tf: Generated HCL with locals and outputs
 *
 * This allows consumers to reference workspace outputs as module outputs:
 *   module.vpc.vpc_id
 */
export async function generateShimModule(
  options: GenerateShimModuleOptions,
): Promise<Uint8Array> {
  const { workspacePath, serial, outputs } = options

  // Generate the main.tf content
  const mainTf = generateMainTf(workspacePath, serial, outputs)

  // Create tar.gz archive
  return createTarGz({
    "main.tf": mainTf,
  })
}

/**
 * Generate the main.tf content for the shim module.
 */
function generateMainTf(
  workspacePath: string,
  serial: number,
  outputs: Record<string, unknown> | null,
): string {
  const timestamp = new Date().toISOString()
  const lines: string[] = [
    "# Generated by Yaffle Module Registry",
    `# Workspace: ${workspacePath}`,
    `# State serial: ${serial}`,
    `# Generated at: ${timestamp}`,
    "#",
    "# Do not edit this file directly. It is regenerated from workspace state.",
    "",
  ]

  // Parse outputs if available
  const parsedOutputs = parseOutputs(outputs)

  if (parsedOutputs.length === 0) {
    lines.push("# No outputs defined in this workspace")
    return lines.join("\n")
  }

  // Generate locals block with baked-in values
  lines.push("locals {")
  lines.push("  # Output values baked in from state")
  lines.push("  _outputs = {")

  for (const { name, value } of parsedOutputs) {
    const hclValue = toHclValue(value)
    lines.push(`    ${name} = ${hclValue}`)
  }

  lines.push("  }")
  lines.push("}")
  lines.push("")

  // Generate output blocks
  for (const { name, type, sensitive } of parsedOutputs) {
    lines.push(`output "${name}" {`)
    lines.push(`  value = local._outputs.${name}`)

    // Add type constraint if we can infer it
    const hclType = inferHclType(type)
    if (hclType) {
      lines.push(`  # type = ${hclType}`)
    }

    if (sensitive) {
      lines.push("  sensitive = true")
    }

    lines.push("}")
    lines.push("")
  }

  return lines.join("\n")
}

/**
 * Parse outputs from state version JSON.
 */
function parseOutputs(
  outputs: Record<string, unknown> | null,
): Array<{ name: string; value: unknown; type: unknown; sensitive: boolean }> {
  if (!outputs || typeof outputs !== "object") {
    return []
  }

  const result: Array<{ name: string; value: unknown; type: unknown; sensitive: boolean }> = []

  for (const [name, output] of Object.entries(outputs)) {
    if (output && typeof output === "object") {
      const tfOutput = output as TerraformOutput
      result.push({
        name,
        value: tfOutput.value,
        type: tfOutput.type,
        sensitive: tfOutput.sensitive ?? false,
      })
    }
  }

  return result
}

/**
 * Convert a JavaScript value to HCL literal syntax.
 */
function toHclValue(value: unknown, indent: number = 4): string {
  if (value === null || value === undefined) {
    return "null"
  }

  if (typeof value === "string") {
    // Escape special characters and wrap in quotes
    const escaped = value
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/\t/g, "\\t")
    return `"${escaped}"`
  }

  if (typeof value === "number") {
    return String(value)
  }

  if (typeof value === "boolean") {
    return value ? "true" : "false"
  }

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return "[]"
    }
    const elements = value.map((v) => toHclValue(v, indent))
    // For simple arrays, use inline format
    if (value.every((v) => typeof v !== "object" || v === null)) {
      return `[${elements.join(", ")}]`
    }
    // For complex arrays, use multiline format
    const padding = " ".repeat(indent)
    return `[\n${padding}  ${elements.join(`,\n${padding}  `)}\n${padding}]`
  }

  if (typeof value === "object") {
    const entries = Object.entries(value)
    if (entries.length === 0) {
      return "{}"
    }
    const padding = " ".repeat(indent)
    const formatted = entries
      .map(([k, v]) => `${padding}  ${quoteIfNeeded(k)} = ${toHclValue(v, indent + 2)}`)
    return `{\n${formatted.join("\n")}\n${padding}}`
  }

  // Fallback for unknown types
  return JSON.stringify(value)
}

/**
 * Quote a key if it's not a valid HCL identifier.
 */
function quoteIfNeeded(key: string): string {
  // HCL identifiers: start with letter/underscore, contain letters/digits/underscores/hyphens
  if (/^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(key)) {
    return key
  }
  return `"${key}"`
}

/**
 * Infer HCL type from Terraform state type annotation.
 *
 * Terraform state stores types as:
 * - "string", "number", "bool" for primitives
 * - ["list", "string"] for list(string)
 * - ["map", "number"] for map(number)
 * - ["set", "string"] for set(string)
 * - ["object", { ... }] for object({ ... })
 * - ["tuple", [ ... ]] for tuple([ ... ])
 */
function inferHclType(type: unknown): string | null {
  if (type === null || type === undefined) {
    return null
  }

  // Primitive types
  if (typeof type === "string") {
    switch (type) {
      case "string":
      case "number":
      case "bool":
        return type
      default:
        return null
    }
  }

  // Complex types: ["list", "string"], etc.
  if (Array.isArray(type) && type.length >= 1) {
    const [kind, elementType] = type

    switch (kind) {
      case "list": {
        const inner = inferHclType(elementType)
        return inner ? `list(${inner})` : "list(any)"
      }
      case "set": {
        const inner = inferHclType(elementType)
        return inner ? `set(${inner})` : "set(any)"
      }
      case "map": {
        const inner = inferHclType(elementType)
        return inner ? `map(${inner})` : "map(any)"
      }
      case "object": {
        // For complex objects, fall back to any
        // A full implementation would recursively build the type
        return "object({...})"
      }
      case "tuple": {
        return "tuple([...])"
      }
      default:
        return null
    }
  }

  return null
}

/**
 * Create a tar.gz archive from a map of filenames to contents.
 *
 * This is a minimal tar implementation that creates POSIX ustar format archives.
 * It's sufficient for our use case of bundling a few text files.
 */
function createTarGz(files: Record<string, string>): Uint8Array {
  const blocks: Buffer[] = []

  for (const [filename, content] of Object.entries(files)) {
    const contentBuf = Buffer.from(content, "utf-8")

    // Create the header block (512 bytes)
    const header = createTarHeader(filename, contentBuf.length)
    blocks.push(header)

    // Add the content
    blocks.push(contentBuf)

    // Pad to 512-byte boundary
    const padding = 512 - (contentBuf.length % 512)
    if (padding < 512) {
      blocks.push(Buffer.alloc(padding, 0))
    }
  }

  // Add two empty blocks to mark end of archive
  blocks.push(Buffer.alloc(1024, 0))

  // Concatenate all blocks
  const tarBuffer = Buffer.concat(blocks)

  // Compress with gzip
  const gzipped = gzipSync(tarBuffer)

  return new Uint8Array(gzipped)
}

/**
 * Create a POSIX ustar tar header for a file.
 */
function createTarHeader(filename: string, size: number): Buffer {
  const header = Buffer.alloc(512, 0)

  // Filename (100 bytes, null-terminated)
  header.write(filename, 0, 100, "utf-8")

  // File mode (8 bytes, octal, null-terminated)
  header.write("0000644\0", 100, 8, "utf-8")

  // UID (8 bytes, octal, null-terminated)
  header.write("0000000\0", 108, 8, "utf-8")

  // GID (8 bytes, octal, null-terminated)
  header.write("0000000\0", 116, 8, "utf-8")

  // Size (12 bytes, octal, null-terminated)
  header.write(size.toString(8).padStart(11, "0") + "\0", 124, 12, "utf-8")

  // Mtime (12 bytes, octal, null-terminated)
  const mtime = Math.floor(Date.now() / 1000)
  header.write(mtime.toString(8).padStart(11, "0") + "\0", 136, 12, "utf-8")

  // Checksum placeholder (8 spaces initially)
  header.write("        ", 148, 8, "utf-8")

  // Type flag (1 byte): '0' = regular file
  header.write("0", 156, 1, "utf-8")

  // Link name (100 bytes, empty for regular files)
  // Already zeroed

  // Magic (6 bytes): "ustar\0"
  header.write("ustar\0", 257, 6, "utf-8")

  // Version (2 bytes): "00"
  header.write("00", 263, 2, "utf-8")

  // Owner name (32 bytes)
  header.write("yaffle", 265, 32, "utf-8")

  // Group name (32 bytes)
  header.write("yaffle", 297, 32, "utf-8")

  // Calculate and write checksum
  let checksum = 0
  for (let i = 0; i < 512; i++) {
    checksum += header[i]
  }
  header.write(checksum.toString(8).padStart(6, "0") + "\0 ", 148, 8, "utf-8")

  return header
}
