import { describe, expect, test } from "@yaffle/test"
import { gunzipSync } from "node:zlib"

import { generateShimModule } from "./module-generator.ts"

/**
 * Unit tests for the module generator.
 *
 * Run with:
 *   pnpm exec vitest run src/lib/module-generator.test.ts
 */

describe("generateShimModule", () => {
  test("generates valid tar.gz archive", async () => {
    const archive = await generateShimModule({
      workspacePath: "test/module",
      serial: 42,
      outputs: {
        example: { value: "hello", type: "string" },
      },
    })

    // Should be a valid gzip (magic bytes 0x1f 0x8b)
    expect(archive[0]).toBe(0x1f)
    expect(archive[1]).toBe(0x8b)

    // Should decompress without error
    const decompressed = gunzipSync(archive)
    expect(decompressed.length).toBeGreaterThan(0)
  })

  test("generates HCL with string output", async () => {
    const archive = await generateShimModule({
      workspacePath: "core/vpc",
      serial: 1,
      outputs: {
        vpc_id: { value: "vpc-123", type: "string" },
      },
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    expect(content).toContain("# Generated by Yaffle Module Registry")
    expect(content).toContain("# Workspace: core/vpc")
    expect(content).toContain("# State serial: 1")
    expect(content).toContain('vpc_id = "vpc-123"')
    expect(content).toContain('output "vpc_id"')
    expect(content).toContain("value = local._outputs.vpc_id")
  })

  test("generates HCL with number output", async () => {
    const archive = await generateShimModule({
      workspacePath: "test",
      serial: 1,
      outputs: {
        count: { value: 42, type: "number" },
      },
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    expect(content).toContain("count = 42")
  })

  test("generates HCL with boolean output", async () => {
    const archive = await generateShimModule({
      workspacePath: "test",
      serial: 1,
      outputs: {
        enabled: { value: true, type: "bool" },
        disabled: { value: false, type: "bool" },
      },
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    expect(content).toContain("enabled = true")
    expect(content).toContain("disabled = false")
  })

  test("generates HCL with list output", async () => {
    const archive = await generateShimModule({
      workspacePath: "test",
      serial: 1,
      outputs: {
        subnet_ids: {
          value: ["subnet-aaa", "subnet-bbb", "subnet-ccc"],
          type: ["list", "string"],
        },
      },
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    expect(content).toContain('subnet_ids = ["subnet-aaa", "subnet-bbb", "subnet-ccc"]')
    expect(content).toContain("# type = list(string)")
  })

  test("generates HCL with map output", async () => {
    const archive = await generateShimModule({
      workspacePath: "test",
      serial: 1,
      outputs: {
        tags: {
          value: { environment: "prod", team: "platform" },
          type: ["map", "string"],
        },
      },
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    expect(content).toContain("tags = {")
    expect(content).toContain('environment = "prod"')
    expect(content).toContain('team = "platform"')
    expect(content).toContain("# type = map(string)")
  })

  test("handles sensitive outputs", async () => {
    const archive = await generateShimModule({
      workspacePath: "test",
      serial: 1,
      outputs: {
        password: { value: "secret123", type: "string", sensitive: true },
      },
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    expect(content).toContain('password = "secret123"')
    expect(content).toContain("sensitive = true")
  })

  test("handles null outputs", async () => {
    const archive = await generateShimModule({
      workspacePath: "test",
      serial: 1,
      outputs: null,
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    expect(content).toContain("# No outputs defined in this workspace")
  })

  test("handles empty outputs", async () => {
    const archive = await generateShimModule({
      workspacePath: "test",
      serial: 1,
      outputs: {},
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    expect(content).toContain("# No outputs defined in this workspace")
  })

  test("escapes special characters in strings", async () => {
    const archive = await generateShimModule({
      workspacePath: "test",
      serial: 1,
      outputs: {
        message: {
          value: 'Hello "world"\nNew line\tTab',
          type: "string",
        },
      },
    })

    const decompressed = gunzipSync(archive)
    const content = extractFileFromTar(decompressed, "main.tf")

    // Should escape quotes and newlines
    expect(content).toContain('\\"world\\"')
    expect(content).toContain("\\n")
    expect(content).toContain("\\t")
  })
})

/**
 * Extract a file from a POSIX tar archive (uncompressed).
 */
function extractFileFromTar(tar: Buffer, filename: string): string {
  let offset = 0

  while (offset < tar.length) {
    // Read the header (512 bytes)
    const header = tar.subarray(offset, offset + 512)

    // Check for end of archive (two null blocks)
    if (header.every((b) => b === 0)) {
      break
    }

    // Extract filename (first 100 bytes, null-terminated)
    const name = header.subarray(0, 100).toString("utf-8").split("\0", 1)[0]

    // Extract size (bytes 124-135, octal string)
    const sizeStr = header.subarray(124, 136).toString("utf-8").split("\0", 1)[0].trim()
    const size = parseInt(sizeStr, 8)

    offset += 512 // Move past header

    if (name === filename) {
      // Found the file, read content
      const content = tar.subarray(offset, offset + size).toString("utf-8")
      return content
    }

    // Skip content and padding
    const paddedSize = Math.ceil(size / 512) * 512
    offset += paddedSize
  }

  throw new Error(`File not found in tar: ${filename}`)
}
