import { join } from "node:path"
import { homedir } from "node:os"
import { mkdir, rm, writeFile, readFile } from "node:fs/promises"
import { existsSync } from "node:fs"

import { logger } from "./telemetry.ts"

// =============================================================================
// Types
// =============================================================================

/**
 * Context for Yaffle-injected provider tags.
 * These are added to all AWS resources via provider default_tags.
 */
export interface YaffleTagContext {
  /** Workspace path, e.g. "infra/shared" */
  workspacePath: string
  /** PR number (undefined for production) */
  prNumber?: number
}

// =============================================================================
// Provider Override (Yaffle Tags)
// =============================================================================

/**
 * Write a provider_override.tf that injects Yaffle-managed tags
 * into AWS provider default_tags. These merge with user-defined tags.
 */
export async function configureProviderOverride(
  tfWorkDir: string,
  ctx: YaffleTagContext,
): Promise<void> {
  const tags: Record<string, string> = {
    yaf_managed: "true",
    yaf_workspace: ctx.workspacePath,
  }

  if (ctx.prNumber !== undefined) {
    tags.yaf_pr = String(ctx.prNumber)
  }

  // Build HCL for the tags
  const tagLines = Object.entries(tags)
    .map(([key, value]) => `      ${key} = "${value}"`)
    .join("\n")

  const overridePath = join(tfWorkDir, "provider_override.tf")
  const overrideContent = `# Generated by Yaffle -- do not edit
# These tags are merged with user-defined default_tags

provider "aws" {
  default_tags {
    tags = {
${tagLines}
    }
  }
}
`
  await writeFile(overridePath, overrideContent)
  logger.info(`provider override written: ${overridePath}`, {
    "provider.override_path": overridePath,
    "provider.workspace": ctx.workspacePath,
    "provider.pr_number": ctx.prNumber ?? "none",
  })
}

// =============================================================================
// Local Backend (dev mode only)
// =============================================================================

const STATE_ROOT = join(homedir(), ".yaffle", "state")

/**
 * Resolve the local state directory for a given owner/repo/stateKey.
 * State key patterns:
 *   - preview-pr-{n}/{workspace}/terraform.tfstate
 *   - {branch}/{workspace}/terraform.tfstate (e.g., main/infra/terraform.tfstate)
 *
 * The local path becomes:
 *   ~/.yaffle/state/{owner}/{repo}/preview-pr-{n}/{workspace}/
 *   ~/.yaffle/state/{owner}/{repo}/{branch}/{workspace}/
 */
export function resolveStateDir(owner: string, repo: string, stateKey: string): string {
  // stateKey is like "preview-pr-42/infra/terraform.tfstate"
  // We want the directory containing the state file
  const dir = stateKey.includes("/")
    ? stateKey.substring(0, stateKey.lastIndexOf("/"))
    : ""
  return join(STATE_ROOT, owner, repo, dir)
}

/**
 * Resolve the full path to the local state file.
 */
export function resolveStatePath(owner: string, repo: string, stateKey: string): string {
  return join(STATE_ROOT, owner, repo, stateKey)
}

/**
 * Ensure the state directory exists and write a backend_override.tf
 * into the terraform working directory that points the local backend
 * at the persistent state path.
 *
 * NOTE: This is only used for local development without the TFC backend.
 * In production, use configureTfcBackend() from tfc-backend.ts instead.
 */
export async function configureLocalBackend(
  tfWorkDir: string,
  owner: string,
  repo: string,
  stateKey: string,
): Promise<string> {
  const statePath = resolveStatePath(owner, repo, stateKey)
  const stateDir = resolveStateDir(owner, repo, stateKey)

  // Ensure the state directory exists
  await mkdir(stateDir, { recursive: true })

  // Write backend override into the TF working directory
  // This tells tofu to use a local backend with our persistent state path
  const overridePath = join(tfWorkDir, "backend_override.tf")
  const overrideContent = `# Generated by Yaffle -- do not edit
terraform {
  backend "local" {
    path = "${statePath}"
  }
}
`
  await writeFile(overridePath, overrideContent)
  logger.info(`backend override written: ${overridePath} -> ${statePath}`, {
    "state.override_path": overridePath,
    "state.state_path": statePath,
    "state.mode": "local",
  })

  return statePath
}

/**
 * Check if a local state file exists for the given key.
 * NOTE: Only works for local backend (dev mode).
 */
export function stateExistsSync(owner: string, repo: string, stateKey: string): boolean {
  return existsSync(resolveStatePath(owner, repo, stateKey))
}

/**
 * Remove the local state directory for a preview (after destroy).
 * NOTE: Only works for local backend (dev mode).
 * In production, workspace state is managed via the TFC API.
 */
export async function removeLocalState(
  owner: string,
  repo: string,
  stateKey: string,
): Promise<void> {
  const stateDir = resolveStateDir(owner, repo, stateKey)
  try {
    await rm(stateDir, { recursive: true, force: true })
    logger.info(`removed state dir: ${stateDir}`, { "state.dir": stateDir })
  } catch (err) {
    logger.warn(`failed to remove state dir ${stateDir}`, {
      "state.dir": stateDir,
      "error": err instanceof Error ? err.message : String(err),
    })
  }
}

// =============================================================================
// Yaffle-Injected Variables
// =============================================================================

/**
 * Write a yaffle_injected_variables.tf that declares Yaffle-injected variables
 * (environment, is_preview) if they're not already declared in the workspace.
 * This prevents "undeclared variable" errors when Yaffle passes these vars.
 *
 * NOTE: We use "yaffle_injected_variables.tf" not "*_override.tf" because
 * Terraform override files can only modify existing declarations, not add new ones.
 */
export async function configureVariablesOverride(
  tfWorkDir: string,
): Promise<void> {
  const variablesToInject = [
    { name: "environment", type: "string", description: "Environment name (injected by Yaffle)" },
    { name: "is_preview", type: "bool", description: "Whether this is a preview environment (injected by Yaffle)" },
  ]

  // Check which variables are already declared by scanning .tf files
  const declaredVars = await findDeclaredVariables(tfWorkDir)

  const missingVars = variablesToInject.filter((v) => !declaredVars.has(v.name))

  if (missingVars.length === 0) {
    logger.debug("all yaffle variables already declared, skipping override", {
      "variables.declared": Array.from(declaredVars).join(", "),
    })
    return
  }

  // Generate HCL for missing variables
  const varBlocks = missingVars
    .map(
      (v) => `variable "${v.name}" {
  type        = ${v.type}
  description = "${v.description}"
}`,
    )
    .join("\n\n")

  const suffix = Math.random().toString(36).substring(2, 10)
  const overridePath = join(tfWorkDir, `yaffle_injected_variables_${suffix}.tf`)
  const overrideContent = `# Generated by Yaffle -- do not edit
# These variables are injected by Yaffle if not declared in the workspace.

${varBlocks}
`

  await writeFile(overridePath, overrideContent)
  logger.info(`variables override written: ${overridePath}`, {
    "variables.override_path": overridePath,
    "variables.injected": missingVars.map((v) => v.name).join(", "),
  })
}

/**
 * Scan .tf files in a directory for declared variables.
 * Returns a Set of variable names.
 */
async function findDeclaredVariables(tfWorkDir: string): Promise<Set<string>> {
  const declared = new Set<string>()
  const { readdir } = await import("node:fs/promises")

  let files: string[]
  try {
    files = await readdir(tfWorkDir)
  } catch {
    return declared
  }

  const tfFiles = files.filter((f) => f.endsWith(".tf") && !f.endsWith("_override.tf"))

  for (const file of tfFiles) {
    try {
      const content = await readFile(join(tfWorkDir, file), "utf-8")
      // Match `variable "name"` declarations
      const matches = content.matchAll(/variable\s+"([^"]+)"/g)
      for (const match of matches) {
        declared.add(match[1])
      }
    } catch {
      // Ignore read errors
    }
  }

  return declared
}
