import { join } from "node:path"
import { homedir } from "node:os"
import { mkdir, rm, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"

import {
  DeleteObjectCommand,
  HeadObjectCommand,
  S3Client,
} from "@aws-sdk/client-s3"

import { logger } from "./telemetry.ts"

// =============================================================================
// Types
// =============================================================================

export type BackendMode = "local" | "s3"

export interface S3BackendConfig {
  bucket: string
  region: string
  dynamodbTable: string
}

export interface BackendConfig {
  mode: BackendMode
  s3?: S3BackendConfig
}

// =============================================================================
// Configuration
// =============================================================================

const STATE_ROOT = join(homedir(), ".yaffle", "state")

/**
 * Detect backend mode from environment.
 * - If STATE_BUCKET is set -> S3 backend
 * - Otherwise -> local backend (dev mode)
 */
export function detectBackendConfig(): BackendConfig {
  const bucket = process.env.STATE_BUCKET
  const region = process.env.AWS_REGION ?? "us-east-1"
  const dynamodbTable = process.env.STATE_LOCK_TABLE ?? "yaffle-locks"

  if (bucket) {
    return {
      mode: "s3",
      s3: { bucket, region, dynamodbTable },
    }
  }

  return { mode: "local" }
}

// Cached S3 client (lazy initialized)
let s3Client: S3Client | undefined

function getS3Client(region: string): S3Client {
  if (!s3Client) {
    s3Client = new S3Client({ region })
  }
  return s3Client
}

// =============================================================================
// Local Backend (dev mode)
// =============================================================================

/**
 * Resolve the local state directory for a given owner/repo/stateKey.
 * State keys follow the PLAN.md convention:
 *   - previews/pr-{n}/terraform.tfstate
 *   - production/main/terraform.tfstate
 *
 * The local path becomes:
 *   ~/.yaffle/state/{owner}/{repo}/previews/pr-{n}/
 *   ~/.yaffle/state/{owner}/{repo}/production/main/
 */
export function resolveStateDir(owner: string, repo: string, stateKey: string): string {
  // stateKey is like "previews/pr-42/terraform.tfstate"
  // We want the directory containing the state file
  const dir = stateKey.includes("/")
    ? stateKey.substring(0, stateKey.lastIndexOf("/"))
    : ""
  return join(STATE_ROOT, owner, repo, dir)
}

/**
 * Resolve the full path to the local state file.
 */
export function resolveStatePath(owner: string, repo: string, stateKey: string): string {
  return join(STATE_ROOT, owner, repo, stateKey)
}

/**
 * Ensure the state directory exists and write a backend_override.tf
 * into the terraform working directory that points the local backend
 * at the persistent state path.
 */
export async function configureLocalBackend(
  tfWorkDir: string,
  owner: string,
  repo: string,
  stateKey: string,
): Promise<string> {
  const statePath = resolveStatePath(owner, repo, stateKey)
  const stateDir = resolveStateDir(owner, repo, stateKey)

  // Ensure the state directory exists
  await mkdir(stateDir, { recursive: true })

  // Write backend override into the TF working directory
  // This tells tofu to use a local backend with our persistent state path
  const overridePath = join(tfWorkDir, "backend_override.tf")
  const overrideContent = `# Generated by Yaffle -- do not edit
terraform {
  backend "local" {
    path = "${statePath}"
  }
}
`
  await writeFile(overridePath, overrideContent)
  logger.info(`backend override written: ${overridePath} -> ${statePath}`, {
    "state.override_path": overridePath,
    "state.state_path": statePath,
    "state.mode": "local",
  })

  return statePath
}

// =============================================================================
// S3 Backend (production)
// =============================================================================

/**
 * Build the S3 state key for a given owner/repo/stateKey.
 * Pattern: {owner}/{repo}/{stateKey}
 *
 * Examples:
 *   - acme/webapp/previews/pr-42/terraform.tfstate
 *   - acme/webapp/production/main/terraform.tfstate
 */
export function resolveS3StateKey(owner: string, repo: string, stateKey: string): string {
  return `${owner}/${repo}/${stateKey}`
}

/**
 * Write a backend_override.tf that configures the S3 backend with
 * DynamoDB locking.
 */
export async function configureS3Backend(
  tfWorkDir: string,
  owner: string,
  repo: string,
  stateKey: string,
  config: S3BackendConfig,
): Promise<string> {
  const s3Key = resolveS3StateKey(owner, repo, stateKey)

  const overridePath = join(tfWorkDir, "backend_override.tf")
  const overrideContent = `# Generated by Yaffle -- do not edit
terraform {
  backend "s3" {
    bucket         = "${config.bucket}"
    key            = "${s3Key}"
    region         = "${config.region}"
    dynamodb_table = "${config.dynamodbTable}"
    encrypt        = true
  }
}
`
  await writeFile(overridePath, overrideContent)
  logger.info(`backend override written: ${overridePath} -> s3://${config.bucket}/${s3Key}`, {
    "state.override_path": overridePath,
    "state.bucket": config.bucket,
    "state.key": s3Key,
    "state.mode": "s3",
  })

  return s3Key
}

// =============================================================================
// Unified Backend API
// =============================================================================

/**
 * Configure the terraform backend for a run.
 * Automatically selects local or S3 based on environment.
 */
export async function configureBackend(
  tfWorkDir: string,
  owner: string,
  repo: string,
  stateKey: string,
  config?: BackendConfig,
): Promise<string> {
  const backendConfig = config ?? detectBackendConfig()

  if (backendConfig.mode === "s3" && backendConfig.s3) {
    return configureS3Backend(tfWorkDir, owner, repo, stateKey, backendConfig.s3)
  }

  return configureLocalBackend(tfWorkDir, owner, repo, stateKey)
}

/**
 * Check if a state file exists for the given key.
 */
export async function stateExists(
  owner: string,
  repo: string,
  stateKey: string,
  config?: BackendConfig,
): Promise<boolean> {
  const backendConfig = config ?? detectBackendConfig()

  if (backendConfig.mode === "s3" && backendConfig.s3) {
    const s3Key = resolveS3StateKey(owner, repo, stateKey)
    const client = getS3Client(backendConfig.s3.region)

    try {
      await client.send(
        new HeadObjectCommand({
          Bucket: backendConfig.s3.bucket,
          Key: s3Key,
        }),
      )
      return true
    } catch (err) {
      // NoSuchKey or 404 means the state doesn't exist
      if (
        err instanceof Error &&
        (err.name === "NotFound" || err.name === "NoSuchKey")
      ) {
        return false
      }
      // Re-throw unexpected errors
      throw err
    }
  }

  // Local backend
  return existsSync(resolveStatePath(owner, repo, stateKey))
}

/**
 * Remove the state for a preview (after destroy).
 */
export async function removeState(
  owner: string,
  repo: string,
  stateKey: string,
  config?: BackendConfig,
): Promise<void> {
  const backendConfig = config ?? detectBackendConfig()

  if (backendConfig.mode === "s3" && backendConfig.s3) {
    const s3Key = resolveS3StateKey(owner, repo, stateKey)
    const client = getS3Client(backendConfig.s3.region)

    try {
      await client.send(
        new DeleteObjectCommand({
          Bucket: backendConfig.s3.bucket,
          Key: s3Key,
        }),
      )
      logger.info(`removed S3 state: s3://${backendConfig.s3.bucket}/${s3Key}`, {
        "state.bucket": backendConfig.s3.bucket,
        "state.key": s3Key,
        "state.mode": "s3",
      })
    } catch (err) {
      logger.warn(`failed to remove S3 state s3://${backendConfig.s3.bucket}/${s3Key}`, {
        "state.bucket": backendConfig.s3.bucket,
        "state.key": s3Key,
        "error": err instanceof Error ? err.message : String(err),
      })
    }
    return
  }

  // Local backend
  const stateDir = resolveStateDir(owner, repo, stateKey)
  try {
    await rm(stateDir, { recursive: true, force: true })
    logger.info(`removed state dir: ${stateDir}`, { "state.dir": stateDir })
  } catch (err) {
    logger.warn(`failed to remove state dir ${stateDir}`, {
      "state.dir": stateDir,
      "error": err instanceof Error ? err.message : String(err),
    })
  }
}

// =============================================================================
// Backwards compatibility exports (deprecated)
// =============================================================================

/**
 * @deprecated Use stateExists() with async/await instead
 */
export function stateExistsSync(owner: string, repo: string, stateKey: string): boolean {
  return existsSync(resolveStatePath(owner, repo, stateKey))
}
