import { join } from "node:path"
import { homedir } from "node:os"
import { mkdir, rm, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"

import { logger } from "./telemetry.ts"

// =============================================================================
// Types
// =============================================================================

/**
 * Context for Yaffle-injected provider tags.
 * These are added to all AWS resources via provider default_tags.
 */
export interface YaffleTagContext {
  /** Workspace path, e.g. "infra/shared" */
  workspacePath: string
  /** Run ID from Yaffle */
  runId?: string
  /** PR number (undefined for production) */
  prNumber?: number
}

// =============================================================================
// Provider Override (Yaffle Tags)
// =============================================================================

/**
 * Write a provider_override.tf that injects Yaffle-managed tags
 * into AWS provider default_tags. These merge with user-defined tags.
 */
export async function configureProviderOverride(
  tfWorkDir: string,
  ctx: YaffleTagContext,
): Promise<void> {
  const tags: Record<string, string> = {
    yaf_managed: "true",
    yaf_workspace: ctx.workspacePath,
  }

  if (ctx.runId) {
    tags.yaf_run_id = ctx.runId
  }

  if (ctx.prNumber !== undefined) {
    tags.yaf_pr = String(ctx.prNumber)
  }

  // Build HCL for the tags
  const tagLines = Object.entries(tags)
    .map(([key, value]) => `      ${key} = "${value}"`)
    .join("\n")

  const overridePath = join(tfWorkDir, "provider_override.tf")
  const overrideContent = `# Generated by Yaffle -- do not edit
# These tags are merged with user-defined default_tags

provider "aws" {
  default_tags {
    tags = {
${tagLines}
    }
  }
}
`
  await writeFile(overridePath, overrideContent)
  logger.info(`provider override written: ${overridePath}`, {
    "provider.override_path": overridePath,
    "provider.workspace": ctx.workspacePath,
    "provider.run_id": ctx.runId ?? "none",
    "provider.pr_number": ctx.prNumber ?? "none",
  })
}

// =============================================================================
// Local Backend (dev mode only)
// =============================================================================

const STATE_ROOT = join(homedir(), ".yaffle", "state")

/**
 * Resolve the local state directory for a given owner/repo/stateKey.
 * State key patterns:
 *   - preview-pr-{n}/{workspace}/terraform.tfstate
 *   - {branch}/{workspace}/terraform.tfstate (e.g., main/infra/terraform.tfstate)
 *
 * The local path becomes:
 *   ~/.yaffle/state/{owner}/{repo}/preview-pr-{n}/{workspace}/
 *   ~/.yaffle/state/{owner}/{repo}/{branch}/{workspace}/
 */
export function resolveStateDir(owner: string, repo: string, stateKey: string): string {
  // stateKey is like "preview-pr-42/infra/terraform.tfstate"
  // We want the directory containing the state file
  const dir = stateKey.includes("/")
    ? stateKey.substring(0, stateKey.lastIndexOf("/"))
    : ""
  return join(STATE_ROOT, owner, repo, dir)
}

/**
 * Resolve the full path to the local state file.
 */
export function resolveStatePath(owner: string, repo: string, stateKey: string): string {
  return join(STATE_ROOT, owner, repo, stateKey)
}

/**
 * Ensure the state directory exists and write a backend_override.tf
 * into the terraform working directory that points the local backend
 * at the persistent state path.
 *
 * NOTE: This is only used for local development without the TFC backend.
 * In production, use configureTfcBackend() from tfc-backend.ts instead.
 */
export async function configureLocalBackend(
  tfWorkDir: string,
  owner: string,
  repo: string,
  stateKey: string,
): Promise<string> {
  const statePath = resolveStatePath(owner, repo, stateKey)
  const stateDir = resolveStateDir(owner, repo, stateKey)

  // Ensure the state directory exists
  await mkdir(stateDir, { recursive: true })

  // Write backend override into the TF working directory
  // This tells tofu to use a local backend with our persistent state path
  const overridePath = join(tfWorkDir, "backend_override.tf")
  const overrideContent = `# Generated by Yaffle -- do not edit
terraform {
  backend "local" {
    path = "${statePath}"
  }
}
`
  await writeFile(overridePath, overrideContent)
  logger.info(`backend override written: ${overridePath} -> ${statePath}`, {
    "state.override_path": overridePath,
    "state.state_path": statePath,
    "state.mode": "local",
  })

  return statePath
}

/**
 * Check if a local state file exists for the given key.
 * NOTE: Only works for local backend (dev mode).
 */
export function stateExistsSync(owner: string, repo: string, stateKey: string): boolean {
  return existsSync(resolveStatePath(owner, repo, stateKey))
}

/**
 * Remove the local state directory for a preview (after destroy).
 * NOTE: Only works for local backend (dev mode).
 * In production, workspace state is managed via the TFC API.
 */
export async function removeLocalState(
  owner: string,
  repo: string,
  stateKey: string,
): Promise<void> {
  const stateDir = resolveStateDir(owner, repo, stateKey)
  try {
    await rm(stateDir, { recursive: true, force: true })
    logger.info(`removed state dir: ${stateDir}`, { "state.dir": stateDir })
  } catch (err) {
    logger.warn(`failed to remove state dir ${stateDir}`, {
      "state.dir": stateDir,
      "error": err instanceof Error ? err.message : String(err),
    })
  }
}
