import { writeFile } from "node:fs/promises"
import { join } from "node:path"

import { logger } from "./telemetry.ts"
import { getTfcApiHost, buildTfTokenEnvName } from "./run-token.ts"

/**
 * Configuration for the TFC cloud backend.
 */
export interface TfcBackendConfig {
  hostname: string
  organization: string
  workspaceName: string
  token: string
}

/**
 * Write a backend_override.tf that configures the Terraform cloud backend
 * to point at Yaffle's TFC-compatible API.
 *
 * @param tfWorkDir - The terraform working directory
 * @param config - TFC backend configuration
 */
export async function configureTfcBackend(
  tfWorkDir: string,
  config: TfcBackendConfig,
): Promise<void> {
  const overridePath = join(tfWorkDir, "backend_override.tf")
  const overrideContent = `# Generated by Yaffle -- do not edit
terraform {
  cloud {
    hostname     = "${config.hostname}"
    organization = "${config.organization}"

    workspaces {
      name = "${config.workspaceName}"
    }
  }
}
`

  await writeFile(overridePath, overrideContent)
  logger.info("TFC backend override written", {
    "backend.override_path": overridePath,
    "backend.hostname": config.hostname,
    "backend.organization": config.organization,
    "backend.workspace": config.workspaceName,
    "backend.mode": "tfc",
  })
}

/**
 * Build environment variables for Terraform to authenticate with Yaffle's TFC API.
 *
 * @param token - The run JWT token
 * @returns Environment variables object to merge with process.env
 */
export function buildTfcEnvVars(token: string): Record<string, string> {
  const hostname = getTfcApiHost()
  const tokenEnvName = buildTfTokenEnvName(hostname)

  return {
    [tokenEnvName]: token,
    // Also set YAFFLE_TFC_API_HOST so it's available in the cloud block
    YAFFLE_TFC_API_HOST: hostname,
  }
}

/**
 * Determine if the TFC backend should be used.
 * Returns true if YAFFLE_TFC_API_HOST is set.
 */
export function useTfcBackend(): boolean {
  return !!process.env.YAFFLE_TFC_API_HOST
}
