[package]
name = "yaffle-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "yaffle"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
base64 = "0.22.1"
clap.workspace = true
clap_complete = "4.5.60"
crossterm = "0.28.1"
getrandom = "0.3.4"
ratatui = "0.29.0"
serde_json.workspace = true
sha2.workspace = true

[dependencies.yaffle-contracts]
path = "../yaffle-contracts"

[dependencies.yaffle-engine]
path = "../yaffle-engine"

[dependencies.yaffle-config]
path = "../yaffle-config"

[dependencies.yaffle-graph]
path = "../yaffle-graph"
