import { join } from "node:path"
import { homedir } from "node:os"
import { mkdir, rm, writeFile } from "node:fs/promises"
import { existsSync } from "node:fs"

import { logger } from "./telemetry.ts"

const STATE_ROOT = join(homedir(), ".yaffle", "state")

/**
 * Resolve the local state directory for a given owner/repo/stateKey.
 * State keys follow the PLAN.md convention:
 *   - previews/pr-{n}/terraform.tfstate
 *   - production/main/terraform.tfstate
 *
 * The local path becomes:
 *   ~/.yaffle/state/{owner}/{repo}/previews/pr-{n}/
 *   ~/.yaffle/state/{owner}/{repo}/production/main/
 */
export function resolveStateDir(owner: string, repo: string, stateKey: string): string {
  // stateKey is like "previews/pr-42/terraform.tfstate"
  // We want the directory containing the state file
  const dir = stateKey.includes("/")
    ? stateKey.substring(0, stateKey.lastIndexOf("/"))
    : ""
  return join(STATE_ROOT, owner, repo, dir)
}

/**
 * Resolve the full path to the state file.
 */
export function resolveStatePath(owner: string, repo: string, stateKey: string): string {
  return join(STATE_ROOT, owner, repo, stateKey)
}

/**
 * Ensure the state directory exists and write a backend_override.tf
 * into the terraform working directory that points the local backend
 * at the persistent state path.
 */
export async function configureLocalBackend(
  tfWorkDir: string,
  owner: string,
  repo: string,
  stateKey: string,
): Promise<string> {
  const statePath = resolveStatePath(owner, repo, stateKey)
  const stateDir = resolveStateDir(owner, repo, stateKey)

  // Ensure the state directory exists
  await mkdir(stateDir, { recursive: true })

  // Write backend override into the TF working directory
  // This tells tofu to use a local backend with our persistent state path
  const overridePath = join(tfWorkDir, "backend_override.tf")
  const overrideContent = `# Generated by Yaffle -- do not edit
terraform {
  backend "local" {
    path = "${statePath}"
  }
}
`
  await writeFile(overridePath, overrideContent)
  logger.info(`backend override written: ${overridePath} -> ${statePath}`, {
    "state.override_path": overridePath,
    "state.state_path": statePath,
  })

  return statePath
}

/**
 * Check if a state file exists for the given key.
 */
export function stateExists(owner: string, repo: string, stateKey: string): boolean {
  return existsSync(resolveStatePath(owner, repo, stateKey))
}

/**
 * Remove the state directory for a preview (after destroy).
 */
export async function removeState(owner: string, repo: string, stateKey: string): Promise<void> {
  const stateDir = resolveStateDir(owner, repo, stateKey)
  try {
    await rm(stateDir, { recursive: true, force: true })
    logger.info(`removed state dir: ${stateDir}`, { "state.dir": stateDir })
  } catch (err) {
    logger.warn(`failed to remove state dir ${stateDir}`, {
      "state.dir": stateDir,
      "error": err instanceof Error ? err.message : String(err),
    })
  }
}
