[package]
name = "yaffle-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true

[dependencies.yaffle-contracts]
path = "../yaffle-contracts"

[dependencies.yaffle-config]
path = "../yaffle-config"

[dependencies.yaffle-graph]
path = "../yaffle-graph"

[dependencies.yaffle-tofu]
path = "../yaffle-tofu"

[dev-dependencies]
tempfile.workspace = true
